project:
  type: website
  output-dir: docs

website:
  title: "Kylie Lay"
  navbar:
    left:
      - href: math-437-project.qmd
        text: Stats Down South (Park)

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    backgroundcolor: "#cec1d2"
    fontcolor: "#511b64"
    linkcolor: "#7e4592"
    mainfont: "sarif"